import type { ProductDefinition, ProductParams, ProductType } from '../types';
import {
  BRACELET_GEMS_ACCENT_COLOR,
  CLICKER_ACCENT_COLOR,
  DEFAULT_COLOR,
  HEAD_KEYCHAINS_ACCENT_COLOR,
  IMAGE_LAYERS_ACCENT_COLOR,
  KEYCHAINS_ACCENT_COLOR,
  LAMP_ACCENT_COLOR,
  PET_KEYCHAINS_ACCENT_COLOR,
  SIGNS_ACCENT_COLOR,
  TEXTURES_ACCENT_COLOR,
  TIP_JAR_ACCENT_COLOR,
  URN_ACCENT_COLOR,
  WIFI_SIGN_ACCENT_COLOR,
} from '../config/constants';
import {
  braceletCharmOptions,
  petKeychainShapeOptions,
} from '../shapes/reusableShapeLibrary';

const LETTER_FONT_OPTIONS = [
  { label: 'Helvetiker Bold', value: 'helvetiker_bold', fontFamily: 'Arial Black, sans-serif' },
  { label: 'Helvetiker', value: 'helvetiker_regular', fontFamily: 'Arial, sans-serif' },
  { label: 'Gentilis', value: 'gentilis_regular', fontFamily: 'Georgia, serif' },
  { label: 'Optimer Bold', value: 'optimer_bold', fontFamily: 'Trebuchet MS, sans-serif' },
  { label: 'Droid Sans Mono', value: 'droid_sans_mono_regular', fontFamily: 'Courier New, monospace' },
  { label: 'Roboto', value: 'roboto_regular', fontFamily: 'Horama Roboto, sans-serif' },
  { label: 'Montserrat', value: 'montserrat_regular', fontFamily: 'Horama Montserrat, sans-serif' },
  { label: 'Open Sans', value: 'open_sans_regular', fontFamily: 'Horama Open Sans, sans-serif' },
  { label: 'Poppins', value: 'poppins_regular', fontFamily: 'Horama Poppins, sans-serif' },
  { label: 'Oswald', value: 'oswald_regular', fontFamily: 'Horama Oswald, sans-serif' },
  { label: 'Lato', value: 'lato_regular', fontFamily: 'Horama Lato, sans-serif' },
  { label: 'Playfair Display', value: 'playfair_display_regular', fontFamily: 'Horama Playfair, serif' },
  { label: 'Bebas Neue', value: 'bebas_neue_regular', fontFamily: 'Horama Bebas Neue, sans-serif' },
  { label: 'Raleway', value: 'raleway_regular', fontFamily: 'Horama Raleway, sans-serif' },
  { label: 'Merriweather', value: 'merriweather_regular', fontFamily: 'Horama Merriweather, serif' },
  { label: 'Lobster', value: 'lobster_regular', fontFamily: 'Horama Lobster, cursive' },
  { label: 'Pacifico', value: 'pacifico_regular', fontFamily: 'Horama Pacifico, cursive' },
  { label: 'Courgette', value: 'courgette_regular', fontFamily: 'Horama Courgette, cursive' },
  { label: 'Kaushan Script', value: 'kaushan_script_regular', fontFamily: 'Horama Kaushan Script, cursive' },
  { label: 'Satisfy', value: 'satisfy_regular', fontFamily: 'Horama Satisfy, cursive' },
  { label: 'Bungee', value: 'bungee_regular', fontFamily: 'Horama Bungee, sans-serif' },
  { label: 'Black Ops One', value: 'black_ops_one_regular', fontFamily: 'Horama Black Ops One, sans-serif' },
  { label: 'Alfa Slab One', value: 'alfa_slab_one_regular', fontFamily: 'Horama Alfa Slab One, serif' },
  { label: 'Luckiest Guy', value: 'luckiest_guy_regular', fontFamily: 'Horama Luckiest Guy, sans-serif' },
  { label: 'Righteous', value: 'righteous_regular', fontFamily: 'Horama Righteous, sans-serif' },
];

const publicAsset = (path: string) =>
  `${import.meta.env.BASE_URL}${path.replace(/^\/+/, '')}`;

export const products: ProductDefinition[] = [
  {
    type: 'lamp',
    name: 'Lamps',
    description: 'Hollow STL models with the fixed Horama lamp mechanism.',
    accent: LAMP_ACCENT_COLOR,
    params: [
      {
        kind: 'color',
        key: 'body_color',
        label: 'Body color',
        defaultValue: DEFAULT_COLOR,
      },
      {
        kind: 'color',
        key: 'base_color',
        label: 'Base color',
        defaultValue: DEFAULT_COLOR,
      },
      {
        kind: 'number',
        key: 'base_thickness_mm',
        label: 'Wall thickness',
        unit: 'mm',
        min: 1,
        max: 20,
        step: 0.5,
        defaultValue: 3,
      },
      {
        kind: 'number',
        key: 'inner_scale',
        label: 'Inner scale',
        min: 0.05,
        max: 0.98,
        step: 0.05,
        defaultValue: 0.7,
      },
      {
        kind: 'number',
        key: 'planar_cut_base_mm',
        label: 'Base cut',
        unit: 'mm',
        min: 0,
        max: 100,
        step: 0.5,
        defaultValue: 8,
      },
      {
        kind: 'number',
        key: 'connector_margin_mm',
        label: 'Connector margin',
        unit: 'mm',
        min: 0,
        max: 20,
        step: 0.5,
        defaultValue: 2,
      },
      {
        kind: 'number',
        key: 'fit_clearance_mm',
        label: 'Fit clearance',
        unit: 'mm',
        min: 0.2,
        max: 2.5,
        step: 0.1,
        defaultValue: 0.9,
      },
      {
        kind: 'number',
        key: 'part_gap_mm',
        label: 'Part gap',
        unit: 'mm',
        min: 0,
        max: 100,
        step: 1,
        defaultValue: 8,
      },
    ],
  },
  {
    type: 'urn',
    name: 'Urns',
    description: 'Local urn transformation with cavity, pressure lid, and ribs.',
    accent: URN_ACCENT_COLOR,
    params: [
      {
        kind: 'select',
        key: 'size',
        label: 'Size',
        defaultValue: 's',
        options: [
          { label: 'Small - 250 ml', value: 's' },
          { label: 'Medium - 500 ml', value: 'm' },
          { label: 'Large - 1000 ml', value: 'l' },
          { label: 'XL - 2000 ml', value: 'xl' },
        ],
      },
      {
        kind: 'text',
        key: 'lid_text',
        label: 'Lid text',
        defaultValue: '',
        multiline: true,
        placeholder: 'add your lid text here',
      },
      {
        kind: 'color',
        key: 'body_color',
        label: 'Body color',
        defaultValue: DEFAULT_COLOR,
      },
      {
        kind: 'color',
        key: 'lid_color',
        label: 'Lid color',
        defaultValue: DEFAULT_COLOR,
      },
      {
        kind: 'color',
        key: 'text_color',
        label: 'Text color',
        defaultValue: '#232629',
      },
      {
        kind: 'number',
        key: 'base_thickness_mm',
        label: 'Base thickness',
        unit: 'mm',
        min: 1,
        max: 12,
        step: 0.5,
        defaultValue: 5,
      },
      {
        kind: 'number',
        key: 'inner_scale',
        label: 'Inner scale',
        min: 0.4,
        max: 0.95,
        step: 0.05,
        defaultValue: 0.7,
      },
      {
        kind: 'number',
        key: 'planar_cut_base_mm',
        label: 'Base cut',
        unit: 'mm',
        min: 0,
        max: 30,
        step: 0.5,
        defaultValue: 8,
      },
    ],
  },
  {
    type: 'clicker',
    name: 'Clickers',
    description: 'Button body, cap size, switch clearance, and keychain options.',
    accent: CLICKER_ACCENT_COLOR,
    params: [
      {
        kind: 'number',
        key: 'stl_scale_percent',
        label: 'STL scale',
        unit: '%',
        min: 10,
        max: 200,
        step: 5,
        defaultValue: 100,
      },
      {
        kind: 'number',
        key: 'cut_height_mm',
        label: 'Cut height',
        unit: 'mm',
        min: 0,
        max: 1,
        step: 0.1,
        defaultValue: 0,
      },
      {
        kind: 'number',
        key: 'base_protrusion_mm',
        label: 'Base protrusion',
        unit: 'mm',
        min: -10,
        max: 10,
        step: 0.1,
        defaultValue: -2,
      },
      {
        kind: 'color',
        key: 'bottom_color',
        label: 'Bottom color',
        defaultValue: DEFAULT_COLOR,
      },
      {
        kind: 'color',
        key: 'top_color',
        label: 'Top color',
        defaultValue: DEFAULT_COLOR,
      },
      {
        kind: 'boolean',
        key: 'keychain_hole',
        label: 'Keychain hole',
        defaultValue: false,
      },
      {
        kind: 'select',
        key: 'keychain_hole_placement',
        label: 'Keychain placement',
        defaultValue: 'bottom',
        options: [
          { label: 'Bottom base', value: 'bottom' },
          { label: 'Top object', value: 'top' },
        ],
      },
      {
        kind: 'number',
        key: 'keychain_hole_angle_deg',
        label: 'Hole position',
        unit: 'deg',
        min: 0,
        max: 360,
        step: 1,
        defaultValue: 0,
      },
      {
        kind: 'number',
        key: 'keychain_hole_inset_mm',
        label: 'Move toward origin',
        unit: 'mm',
        min: 0,
        max: 24,
        step: 0.5,
        defaultValue: 0,
      },
    ],
  },
  {
    type: 'head_keychains',
    name: 'Head Keychains',
    description: 'Cut a head from a bust STL and add a keychain ring on top.',
    accent: HEAD_KEYCHAINS_ACCENT_COLOR,
    params: [
      {
        kind: 'number',
        key: 'stl_scale_percent',
        label: 'STL scale',
        unit: '%',
        min: 10,
        max: 200,
        step: 5,
        defaultValue: 100,
      },
      {
        kind: 'number',
        key: 'cut_height_mm',
        label: 'Cut height',
        unit: 'mm',
        min: 0,
        max: 1,
        step: 0.1,
        defaultValue: 0,
      },
      {
        kind: 'select',
        key: 'head_keychain_attachment',
        label: 'Keychain attachment',
        defaultValue: 'exterior_ring',
        options: [
          { label: 'Exterior ring', value: 'exterior_ring' },
          { label: 'Integrated hole', value: 'integrated_hole' },
        ],
      },
      {
        kind: 'number',
        key: 'ring_outer_diameter_mm',
        label: 'Ring outer diameter',
        unit: 'mm',
        min: 2,
        max: 20,
        step: 0.5,
        defaultValue: 6,
      },
      {
        kind: 'number',
        key: 'ring_offset_x_mm',
        label: 'Move ring on X',
        unit: 'mm',
        min: -50,
        max: 50,
        step: 0.5,
        defaultValue: 0,
      },
      {
        kind: 'number',
        key: 'ring_offset_y_mm',
        label: 'Move ring on Y',
        unit: 'mm',
        min: -50,
        max: 50,
        step: 0.5,
        defaultValue: 0,
      },
      {
        kind: 'number',
        key: 'head_hole_diameter_mm',
        label: 'Hole diameter',
        unit: 'mm',
        min: 1.5,
        max: 10,
        step: 0.5,
        defaultValue: 3,
      },
      {
        kind: 'number',
        key: 'head_hole_offset_x_mm',
        label: 'Move hole on X',
        unit: 'mm',
        min: -50,
        max: 50,
        step: 0.5,
        defaultValue: 0,
      },
      {
        kind: 'number',
        key: 'head_hole_offset_z_mm',
        label: 'Move hole vertically',
        unit: 'mm',
        min: -50,
        max: 50,
        step: 0.5,
        defaultValue: 0,
      },
    ],
  },
  {
    type: 'textures',
    name: 'Textures',
    description: 'Raised printable surface patterns from the generic transform flow.',
    accent: TEXTURES_ACCENT_COLOR,
    params: [
      {
        kind: 'select',
        key: 'texture',
        label: 'Texture',
        defaultValue: 'woven',
        options: [
          { label: 'Woven', value: 'woven', preview: publicAsset('textures/woven.svg') },
          { label: 'Knit', value: 'knit', preview: publicAsset('textures/knit.svg') },
          { label: 'Carbon', value: 'carbon', preview: publicAsset('textures/carbon.svg') },
          { label: 'Wood', value: 'wood', preview: publicAsset('textures/wood.svg') },
          { label: 'None', value: 'none', preview: publicAsset('textures/none.svg') },
        ],
      },
      {
        kind: 'number',
        key: 'texture_depth_mm',
        label: 'Relief depth',
        unit: 'mm',
        min: 0.1,
        max: 1.2,
        step: 0.05,
        defaultValue: 0.45,
      },
      {
        kind: 'number',
        key: 'texture_spacing_mm',
        label: 'Pattern spacing',
        unit: 'mm',
        min: 1,
        max: 8,
        step: 0.25,
        defaultValue: 3,
      },
    ],
  },
  {
    type: 'keychains',
    name: 'Keychains',
    description: 'Standalone keychain tools coming soon.',
    accent: KEYCHAINS_ACCENT_COLOR,
    params: [],
  },
  {
    type: 'image_layers',
    name: 'Image to Layers',
    description: 'Convert a reduced-color image into stacked printable color layers.',
    accent: IMAGE_LAYERS_ACCENT_COLOR,
    params: [
      { kind: 'number', key: 'color_count', label: 'Material colors', min: 2, max: 16, step: 1, defaultValue: 8 },
      { kind: 'number', key: 'width_mm', label: 'Printed width', unit: 'mm', min: 20, max: 400, step: 1, defaultValue: 120 },
      { kind: 'number', key: 'layer_height_mm', label: 'Layer height', unit: 'mm', min: 0.2, max: 5, step: 0.2, defaultValue: 1.2 },
      {
        kind: 'select', key: 'detail_preset', label: 'Detail', defaultValue: 'balanced',
        options: [
          { label: 'Draft', value: 'draft' },
          { label: 'Balanced', value: 'balanced' },
          { label: 'High', value: 'high' },
        ],
      },
      { kind: 'number', key: 'frame_width_mm', label: 'Frame width', unit: 'mm', min: 0, max: 30, step: 0.5, defaultValue: 4 },
      {
        kind: 'select', key: 'background_strategy', label: 'Background', defaultValue: 'border',
        options: [
          { label: 'Detect from border', value: 'border' },
          { label: 'Dominant color', value: 'dominant' },
          { label: 'No full backing', value: 'none' },
        ],
      },
      {
        kind: 'select', key: 'layer_order_strategy', label: 'Layer order', defaultValue: 'dark_on_top',
        options: [
          { label: 'Dark details on top', value: 'dark_on_top' },
          { label: 'Light details on top', value: 'light_on_top' },
        ],
      },
      { kind: 'boolean', key: 'top_border', label: 'Raised top border', defaultValue: true },
      { kind: 'number', key: 'top_border_height_mm', label: 'Top border height', unit: 'mm', min: 0.2, max: 20, step: 0.2, defaultValue: 3 },
    ],
  },
  {
    type: 'signs',
    name: 'Signs',
    description: 'Custom letter signs with local fonts, hollow walls, and textures.',
    accent: SIGNS_ACCENT_COLOR,
    params: [
      {
        kind: 'text',
        key: 'text',
        label: 'Sign text',
        defaultValue: 'HORAMA',
        multiline: true,
        placeholder: 'Type the sign text',
      },
      {
        kind: 'select',
        key: 'font',
        label: 'Font',
        defaultValue: 'helvetiker_bold',
        options: LETTER_FONT_OPTIONS,
      },
      {
        kind: 'number',
        key: 'font_size_mm',
        label: 'Letter size',
        unit: 'mm',
        min: 10,
        max: 320,
        step: 1,
        defaultValue: 60,
      },
      {
        kind: 'number',
        key: 'letter_spacing_mm',
        label: 'Letter spacing',
        unit: 'mm',
        min: -5,
        max: 30,
        step: 0.5,
        defaultValue: 2,
      },
      {
        kind: 'number',
        key: 'line_spacing_mm',
        label: 'Line spacing',
        unit: 'mm',
        min: 0,
        max: 80,
        step: 1,
        defaultValue: 10,
      },
      {
        kind: 'number',
        key: 'base_thickness_mm',
        label: 'Base thickness',
        unit: 'mm',
        min: 0.8,
        max: 12,
        step: 0.2,
        defaultValue: 2.4,
      },
      {
        kind: 'select',
        key: 'sign_mode',
        label: 'Letter construction',
        defaultValue: 'solid',
        options: [
          { label: 'Solid letters', value: 'solid' },
          { label: 'Hollow letters', value: 'hollow' },
          { label: 'Blind mounting holes', value: 'mounting_holes' },
        ],
      },
      {
        kind: 'boolean',
        key: 'mirror_hollow',
        label: 'Mirror letters',
        help: 'Mirrors hollow letters so they read correctly when the open side faces the wall or is filled with LEDs.',
        defaultValue: false,
      },
      {
        kind: 'number',
        key: 'mounting_hole_diameter_mm',
        label: 'Hole diameter',
        unit: 'mm',
        min: 2,
        max: 12,
        step: 0.5,
        defaultValue: 6,
      },
      {
        kind: 'number',
        key: 'mounting_hole_depth_mm',
        label: 'Hole depth',
        unit: 'mm',
        help: 'The cavity stays blind and always keeps a solid front skin.',
        min: 1,
        max: 40,
        step: 0.5,
        defaultValue: 6,
      },
      {
        kind: 'number',
        key: 'wall_thickness_mm',
        label: 'Wall thickness',
        unit: 'mm',
        min: 0.8,
        max: 6,
        step: 0.2,
        defaultValue: 1.6,
      },
      {
        kind: 'number',
        key: 'wall_height_mm',
        label: 'Wall height',
        unit: 'mm',
        min: 1,
        max: 80,
        step: 1,
        defaultValue: 20,
      },
      {
        kind: 'select',
        key: 'texture',
        label: 'Surface texture',
        defaultValue: 'none',
        options: [
          { label: 'None', value: 'none', preview: publicAsset('textures/none.svg') },
          { label: 'Woven', value: 'woven', preview: publicAsset('textures/woven.svg') },
          { label: 'Knit', value: 'knit', preview: publicAsset('textures/knit.svg') },
          { label: 'Carbon', value: 'carbon', preview: publicAsset('textures/carbon.svg') },
          { label: 'Wood', value: 'wood', preview: publicAsset('textures/wood.svg') },
        ],
      },
      {
        kind: 'number',
        key: 'texture_depth_mm',
        label: 'Texture depth',
        unit: 'mm',
        min: 0.2,
        max: 2.5,
        step: 0.1,
        defaultValue: 0.8,
      },
      {
        kind: 'number',
        key: 'texture_spacing_mm',
        label: 'Texture spacing',
        unit: 'mm',
        min: 1,
        max: 8,
        step: 0.25,
        defaultValue: 3,
      },
    ],
  },
  {
    type: 'pet_keychains',
    name: 'Pet Keychains',
    description: 'Personalized pet tags with a movable keychain hole.',
    accent: PET_KEYCHAINS_ACCENT_COLOR,
    params: [
      {
        kind: 'select',
        key: 'pet_shape',
        label: 'Shape',
        defaultValue: 'bone',
        options: petKeychainShapeOptions,
      },
      {
        kind: 'text',
        key: 'text',
        label: 'Pet name',
        defaultValue: 'LUNA',
        placeholder: 'Type a pet name',
      },
      {
        kind: 'select',
        key: 'font',
        label: 'Font',
        defaultValue: 'helvetiker_bold',
        options: LETTER_FONT_OPTIONS,
      },
      {
        kind: 'number',
        key: 'tag_width_mm',
        label: 'Tag width',
        unit: 'mm',
        min: 20,
        max: 100,
        step: 1,
        defaultValue: 60,
      },
      {
        kind: 'number',
        key: 'base_thickness_mm',
        label: 'Base thickness',
        unit: 'mm',
        min: 1.6,
        max: 8,
        step: 0.2,
        defaultValue: 3,
      },
      {
        kind: 'number',
        key: 'text_height_mm',
        label: 'Text relief',
        unit: 'mm',
        min: 0.4,
        max: 4,
        step: 0.2,
        defaultValue: 1.2,
      },
      {
        kind: 'number',
        key: 'keychain_hole_diameter_mm',
        label: 'Hole diameter',
        unit: 'mm',
        help: 'Drag the orange hole in the 3D preview to place it.',
        min: 3,
        max: 10,
        step: 0.5,
        defaultValue: 5,
      },
      {
        kind: 'color',
        key: 'body_color',
        label: 'Tag color',
        defaultValue: '#e8794f',
      },
      {
        kind: 'color',
        key: 'text_color',
        label: 'Name color',
        defaultValue: '#fff4dc',
      },
    ],
  },
  {
    type: 'bracelet_gems',
    name: 'Bracelet Gems',
    description: 'Threadable name gems for backpacks, lunch bags, and keychains.',
    accent: BRACELET_GEMS_ACCENT_COLOR,
    params: [
      {
        kind: 'text',
        key: 'text',
        label: 'Name or text',
        defaultValue: 'HORAMA',
        placeholder: 'Type a name',
      },
      {
        kind: 'select',
        key: 'font',
        label: 'Font',
        defaultValue: 'helvetiker_bold',
        options: LETTER_FONT_OPTIONS,
      },
      {
        kind: 'number',
        key: 'gem_width_mm',
        label: 'Gem width',
        unit: 'mm',
        min: 10,
        max: 30,
        step: 0.5,
        defaultValue: 13,
      },
      {
        kind: 'number',
        key: 'gem_height_mm',
        label: 'Gem height',
        unit: 'mm',
        min: 18,
        max: 45,
        step: 0.5,
        defaultValue: 25,
      },
      {
        kind: 'number',
        key: 'gem_thickness_mm',
        label: 'Z height',
        unit: 'mm',
        help: 'Controls the printed height on the Z axis. For 25 mm letters, 4–6 mm is recommended.',
        min: 3,
        max: 15,
        step: 0.25,
        defaultValue: 5,
      },
      {
        kind: 'select',
        key: 'thread_orientation',
        label: 'Thread orientation',
        defaultValue: 'vertical',
        options: [
          { label: 'Vertical — holes top and bottom', value: 'vertical' },
          { label: 'Horizontal — holes on the sides', value: 'horizontal' },
        ],
      },
      {
        kind: 'number',
        key: 'piece_spacing_mm',
        label: 'Piece spacing',
        unit: 'mm',
        min: 1,
        max: 12,
        step: 0.5,
        defaultValue: 3,
      },
      {
        kind: 'boolean',
        key: 'cord_stops',
        label: 'Cord stops',
        help: 'Adds one cord stop before and after the letters.',
        defaultValue: true,
      },
      {
        kind: 'select',
        key: 'bracelet_charms',
        label: 'Threadable charms',
        help: 'Add independent decorative pieces. They do not replace the cord stops.',
        defaultValue: '{}',
        options: braceletCharmOptions,
      },
      {
        kind: 'color',
        key: 'body_color',
        label: 'Preview color',
        defaultValue: '#b978d0',
      },
    ],
  },
  {
    type: 'tip_jar',
    name: 'Tip Jars',
    description: 'Custom tip jars with a removable lid, real QR code, and NFC marker.',
    accent: TIP_JAR_ACCENT_COLOR,
    params: [
      {
        kind: 'select',
        key: 'tip_jar_version',
        label: 'Version',
        defaultValue: 'qr_nfc',
        options: [
          { label: 'Basic', value: 'basic' },
          { label: 'Custom QR', value: 'qr' },
          { label: 'QR + NFC', value: 'qr_nfc' },
          { label: 'Premium multicolor', value: 'premium' },
        ],
      },
      {
        kind: 'text',
        key: 'business_name',
        label: 'Business name',
        defaultValue: 'TU NEGOCIO',
        placeholder: 'Type your business name',
      },
      {
        kind: 'text',
        key: 'tip_message',
        label: 'Thank-you message',
        defaultValue: 'GRACIAS',
        placeholder: 'Thank you for your tip',
      },
      {
        kind: 'text',
        key: 'qr_url',
        label: 'QR destination',
        help: 'Enter the payment, social media, menu, or contact link.',
        defaultValue: 'https://horama3d.com',
        placeholder: 'https://...',
      },
      {
        kind: 'select',
        key: 'font',
        label: 'Font',
        defaultValue: 'helvetiker_bold',
        options: LETTER_FONT_OPTIONS,
      },
      {
        kind: 'number',
        key: 'wall_thickness_mm',
        label: 'Wall thickness',
        unit: 'mm',
        min: 1.6,
        max: 5,
        step: 0.2,
        defaultValue: 2.4,
      },
      {
        kind: 'number',
        key: 'base_thickness_mm',
        label: 'Base thickness',
        unit: 'mm',
        min: 2,
        max: 8,
        step: 0.2,
        defaultValue: 3.2,
      },
      {
        kind: 'number',
        key: 'lid_thickness_mm',
        label: 'Lid thickness',
        unit: 'mm',
        min: 2.4,
        max: 8,
        step: 0.2,
        defaultValue: 4,
      },
      {
        kind: 'number',
        key: 'fit_clearance_mm',
        label: 'Fit clearance',
        unit: 'mm',
        help: 'Increase this value if the printed lid fits too tightly.',
        min: 0.2,
        max: 1.5,
        step: 0.05,
        defaultValue: 0.55,
      },
      {
        kind: 'color',
        key: 'body_color',
        label: 'Body color',
        defaultValue: '#151515',
      },
      {
        kind: 'color',
        key: 'lid_color',
        label: 'Lid and panel color',
        defaultValue: '#d5b72f',
      },
      {
        kind: 'color',
        key: 'text_color',
        label: 'Text and NFC color',
        defaultValue: '#ffffff',
      },
      {
        kind: 'color',
        key: 'qr_color',
        label: 'QR color',
        defaultValue: '#171717',
      },
    ],
  },
  {
    type: 'wifi_sign',
    name: 'WiFi QR Signs',
    description: 'Rounded signs with a real WiFi QR code and optional visible credentials.',
    accent: WIFI_SIGN_ACCENT_COLOR,
    params: [
      {
        kind: 'select',
        key: 'wifi_sign_size',
        label: 'Sign size',
        defaultValue: 'standard',
        options: [
          { label: 'Compact — 120 × 150 mm', value: 'compact' },
          { label: 'Standard — 150 × 180 mm', value: 'standard' },
          { label: 'Large — 180 × 220 mm', value: 'large' },
        ],
      },
      {
        kind: 'text',
        key: 'wifi_title',
        label: 'Sign title',
        defaultValue: 'Casa Monte Alban',
        placeholder: 'Business, home, or event name',
      },
      {
        kind: 'text',
        key: 'wifi_label',
        label: 'WiFi label',
        defaultValue: 'WiFi',
        placeholder: 'WiFi',
      },
      {
        kind: 'text',
        key: 'wifi_ssid',
        label: 'Network name (SSID)',
        defaultValue: 'MI RED WIFI',
        placeholder: 'Network name',
      },
      {
        kind: 'text',
        key: 'wifi_password',
        label: 'WiFi password',
        defaultValue: 'CONTRASEÑA',
        placeholder: 'Network password',
      },
      {
        kind: 'select',
        key: 'wifi_security',
        label: 'Security',
        defaultValue: 'WPA',
        options: [
          { label: 'WPA / WPA2 / WPA3', value: 'WPA' },
          { label: 'WEP', value: 'WEP' },
          { label: 'Open network', value: 'nopass' },
        ],
      },
      {
        kind: 'boolean',
        key: 'wifi_hidden',
        label: 'Hidden network',
        defaultValue: false,
      },
      {
        kind: 'boolean',
        key: 'show_credentials',
        label: 'Show credentials on sign',
        help: 'Turn this off to keep the network name and password inside the QR only.',
        defaultValue: true,
      },
      {
        kind: 'select',
        key: 'font',
        label: 'Title font',
        defaultValue: 'playfair_display_regular',
        options: LETTER_FONT_OPTIONS,
      },
      {
        kind: 'number',
        key: 'base_thickness_mm',
        label: 'Base thickness',
        unit: 'mm',
        min: 1.6,
        max: 8,
        step: 0.2,
        defaultValue: 3.2,
      },
      {
        kind: 'number',
        key: 'relief_height_mm',
        label: 'Detail relief',
        unit: 'mm',
        min: 0.4,
        max: 2.4,
        step: 0.2,
        defaultValue: 0.8,
      },
      {
        kind: 'number',
        key: 'corner_radius_mm',
        label: 'Corner radius',
        unit: 'mm',
        min: 1,
        max: 20,
        step: 0.5,
        defaultValue: 7,
      },
      {
        kind: 'color',
        key: 'base_color',
        label: 'Sign color',
        defaultValue: '#e7a0b4',
      },
      {
        kind: 'color',
        key: 'detail_color',
        label: 'Text and QR color',
        defaultValue: '#171717',
      },
    ],
  },
];

export function getProduct(type: ProductType): ProductDefinition {
  const product = products.find((item) => item.type === type);
  if (!product) throw new Error(`Unknown product type: ${type}`);
  return product;
}

export function getDefaultParams(product: ProductDefinition): ProductParams {
  return Object.fromEntries(
    product.params.map((param) => [param.key, param.defaultValue]),
  );
}
