import type { ProductDefinition, ProductParams, ProductType } from '../types';
import {
  CLICKER_ACCENT_COLOR,
  DEFAULT_COLOR,
  IMAGE_LAYERS_ACCENT_COLOR,
  KEYCHAINS_ACCENT_COLOR,
  SIGNS_ACCENT_COLOR,
  TEXTURES_ACCENT_COLOR,
  URN_ACCENT_COLOR,
} from '../config/constants';

export const products: ProductDefinition[] = [
  {
    type: 'urn',
    name: 'Urns',
    description: 'Urn transform settings from the STP urn workflow.',
    accent: URN_ACCENT_COLOR,
    params: [
      {
        kind: 'select',
        key: 'size',
        label: 'Size',
        defaultValue: 's',
        options: [
          { label: 'Small - 250 ml', value: 's' },
          { label: 'Medium - 500 ml', value: 'm' },
          { label: 'Large - 1000 ml', value: 'l' },
          { label: 'XL - 2000 ml', value: 'xl' },
        ],
      },
      {
        kind: 'text',
        key: 'lid_text',
        label: 'Lid text',
        defaultValue: '',
        multiline: true,
        placeholder: 'add your lid text here',
      },
      {
        kind: 'color',
        key: 'body_color',
        label: 'Body color',
        defaultValue: DEFAULT_COLOR,
      },
      {
        kind: 'color',
        key: 'lid_color',
        label: 'Lid color',
        defaultValue: DEFAULT_COLOR,
      },
      {
        kind: 'color',
        key: 'text_color',
        label: 'Text color',
        defaultValue: '#232629',
      },
      {
        kind: 'number',
        key: 'base_thickness_mm',
        label: 'Base thickness',
        unit: 'mm',
        min: 1,
        max: 12,
        step: 0.5,
        defaultValue: 5,
      },
      {
        kind: 'number',
        key: 'inner_scale',
        label: 'Inner scale',
        min: 0.4,
        max: 0.95,
        step: 0.05,
        defaultValue: 0.7,
      },
      {
        kind: 'number',
        key: 'planar_cut_base_mm',
        label: 'Base cut',
        unit: 'mm',
        min: 0,
        max: 30,
        step: 0.5,
        defaultValue: 8,
      },
    ],
  },
  {
    type: 'clicker',
    name: 'Clickers',
    description: 'Button body, cap size, switch clearance, and keychain options.',
    accent: CLICKER_ACCENT_COLOR,
    params: [
      {
        kind: 'number',
        key: 'cut_height_mm',
        label: 'Cut height',
        unit: 'mm',
        min: 0,
        max: 1,
        step: 0.1,
        defaultValue: 0,
      },
      {
        kind: 'number',
        key: 'base_protrusion_mm',
        label: 'Base protrusion',
        unit: 'mm',
        min: -10,
        max: 10,
        step: 0.1,
        defaultValue: -2,
      },
      {
        kind: 'color',
        key: 'bottom_color',
        label: 'Bottom color',
        defaultValue: DEFAULT_COLOR,
      },
      {
        kind: 'color',
        key: 'top_color',
        label: 'Top color',
        defaultValue: DEFAULT_COLOR,
      },
      {
        kind: 'boolean',
        key: 'keychain_hole',
        label: 'Keychain hole',
        defaultValue: false,
      },
      {
        kind: 'select',
        key: 'keychain_hole_placement',
        label: 'Keychain placement',
        defaultValue: 'bottom',
        options: [
          { label: 'Bottom base', value: 'bottom' },
          { label: 'Top object', value: 'top' },
        ],
      },
      {
        kind: 'number',
        key: 'keychain_hole_angle_deg',
        label: 'Hole position',
        unit: 'deg',
        min: 0,
        max: 360,
        step: 1,
        defaultValue: 0,
      },
      {
        kind: 'number',
        key: 'keychain_hole_inset_mm',
        label: 'Move toward origin',
        unit: 'mm',
        min: 0,
        max: 24,
        step: 0.5,
        defaultValue: 0,
      },
    ],
  },
  {
    type: 'textures',
    name: 'Textures',
    description: 'Raised printable surface patterns from the generic transform flow.',
    accent: TEXTURES_ACCENT_COLOR,
    params: [
      {
        kind: 'select',
        key: 'texture',
        label: 'Texture',
        defaultValue: 'woven',
        options: [
          { label: 'Woven', value: 'woven', preview: '/textures/woven.svg' },
          { label: 'Knit', value: 'knit', preview: '/textures/knit.svg' },
          { label: 'Carbon', value: 'carbon', preview: '/textures/carbon.svg' },
          { label: 'Wood', value: 'wood', preview: '/textures/wood.svg' },
          { label: 'None', value: 'none', preview: '/textures/none.svg' },
        ],
      },
      {
        kind: 'number',
        key: 'texture_depth_mm',
        label: 'Relief depth',
        unit: 'mm',
        min: 0.1,
        max: 1.2,
        step: 0.05,
        defaultValue: 0.45,
      },
      {
        kind: 'number',
        key: 'texture_spacing_mm',
        label: 'Pattern spacing',
        unit: 'mm',
        min: 1,
        max: 8,
        step: 0.25,
        defaultValue: 3,
      },
    ],
  },
  {
    type: 'keychains',
    name: 'Keychains',
    description: 'Standalone keychain tools coming soon.',
    accent: KEYCHAINS_ACCENT_COLOR,
    params: [],
  },
  {
    type: 'image_layers',
    name: 'Image to Layers',
    description: 'Convert an image into separated printable depth layers.',
    accent: IMAGE_LAYERS_ACCENT_COLOR,
    params: [],
  },
  {
    type: 'signs',
    name: 'Signs',
    description: 'Custom letter signs with local fonts, hollow walls, and textures.',
    accent: SIGNS_ACCENT_COLOR,
    params: [
      {
        kind: 'text',
        key: 'text',
        label: 'Sign text',
        defaultValue: 'HORAMA',
        multiline: true,
        placeholder: 'Type the sign text',
      },
      {
        kind: 'select',
        key: 'font',
        label: 'Font',
        defaultValue: 'helvetiker_bold',
        options: [
          { label: 'Helvetiker Bold', value: 'helvetiker_bold', fontFamily: 'Arial Black, sans-serif' },
          { label: 'Helvetiker', value: 'helvetiker_regular', fontFamily: 'Arial, sans-serif' },
          { label: 'Gentilis', value: 'gentilis_regular', fontFamily: 'Georgia, serif' },
          { label: 'Optimer Bold', value: 'optimer_bold', fontFamily: 'Trebuchet MS, sans-serif' },
          { label: 'Droid Sans Mono', value: 'droid_sans_mono_regular', fontFamily: 'Courier New, monospace' },
          { label: 'Roboto', value: 'roboto_regular', fontFamily: 'Horama Roboto, sans-serif' },
          { label: 'Montserrat', value: 'montserrat_regular', fontFamily: 'Horama Montserrat, sans-serif' },
          { label: 'Open Sans', value: 'open_sans_regular', fontFamily: 'Horama Open Sans, sans-serif' },
          { label: 'Poppins', value: 'poppins_regular', fontFamily: 'Horama Poppins, sans-serif' },
          { label: 'Oswald', value: 'oswald_regular', fontFamily: 'Horama Oswald, sans-serif' },
          { label: 'Lato', value: 'lato_regular', fontFamily: 'Horama Lato, sans-serif' },
          { label: 'Playfair Display', value: 'playfair_display_regular', fontFamily: 'Horama Playfair, serif' },
          { label: 'Bebas Neue', value: 'bebas_neue_regular', fontFamily: 'Horama Bebas Neue, sans-serif' },
          { label: 'Raleway', value: 'raleway_regular', fontFamily: 'Horama Raleway, sans-serif' },
          { label: 'Merriweather', value: 'merriweather_regular', fontFamily: 'Horama Merriweather, serif' },
          { label: 'Lobster', value: 'lobster_regular', fontFamily: 'Horama Lobster, cursive' },
          { label: 'Pacifico', value: 'pacifico_regular', fontFamily: 'Horama Pacifico, cursive' },
          { label: 'Courgette', value: 'courgette_regular', fontFamily: 'Horama Courgette, cursive' },
          { label: 'Kaushan Script', value: 'kaushan_script_regular', fontFamily: 'Horama Kaushan Script, cursive' },
          { label: 'Satisfy', value: 'satisfy_regular', fontFamily: 'Horama Satisfy, cursive' },
          { label: 'Bungee', value: 'bungee_regular', fontFamily: 'Horama Bungee, sans-serif' },
          { label: 'Black Ops One', value: 'black_ops_one_regular', fontFamily: 'Horama Black Ops One, sans-serif' },
          { label: 'Alfa Slab One', value: 'alfa_slab_one_regular', fontFamily: 'Horama Alfa Slab One, serif' },
          { label: 'Luckiest Guy', value: 'luckiest_guy_regular', fontFamily: 'Horama Luckiest Guy, sans-serif' },
          { label: 'Righteous', value: 'righteous_regular', fontFamily: 'Horama Righteous, sans-serif' },
        ],
      },
      {
        kind: 'number',
        key: 'font_size_mm',
        label: 'Letter size',
        unit: 'mm',
        min: 10,
        max: 320,
        step: 1,
        defaultValue: 60,
      },
      {
        kind: 'number',
        key: 'letter_spacing_mm',
        label: 'Letter spacing',
        unit: 'mm',
        min: -5,
        max: 30,
        step: 0.5,
        defaultValue: 2,
      },
      {
        kind: 'number',
        key: 'line_spacing_mm',
        label: 'Line spacing',
        unit: 'mm',
        min: 0,
        max: 80,
        step: 1,
        defaultValue: 10,
      },
      {
        kind: 'number',
        key: 'base_thickness_mm',
        label: 'Base thickness',
        unit: 'mm',
        min: 0.8,
        max: 12,
        step: 0.2,
        defaultValue: 2.4,
      },
      {
        kind: 'boolean',
        key: 'hollow',
        label: 'Hollow letters',
        help: 'Keeps a thin base and perimeter walls so the letters use less material.',
        defaultValue: false,
      },
      {
        kind: 'boolean',
        key: 'mounting_holes',
        label: 'Blind mounting holes',
        help: 'Adds a centered blind cavity behind each letter for balanced nail mounting.',
        defaultValue: false,
      },
      {
        kind: 'number',
        key: 'mounting_hole_diameter_mm',
        label: 'Hole diameter',
        unit: 'mm',
        min: 2,
        max: 12,
        step: 0.5,
        defaultValue: 6,
      },
      {
        kind: 'number',
        key: 'mounting_hole_depth_mm',
        label: 'Hole depth',
        unit: 'mm',
        help: 'The cavity stays blind and always keeps a solid front skin.',
        min: 1,
        max: 40,
        step: 0.5,
        defaultValue: 6,
      },
      {
        kind: 'number',
        key: 'wall_thickness_mm',
        label: 'Wall thickness',
        unit: 'mm',
        min: 0.8,
        max: 6,
        step: 0.2,
        defaultValue: 1.6,
      },
      {
        kind: 'number',
        key: 'wall_height_mm',
        label: 'Wall height',
        unit: 'mm',
        min: 1,
        max: 80,
        step: 1,
        defaultValue: 20,
      },
      {
        kind: 'select',
        key: 'texture',
        label: 'Surface texture',
        defaultValue: 'none',
        options: [
          { label: 'None', value: 'none', preview: '/textures/none.svg' },
          { label: 'Woven', value: 'woven', preview: '/textures/woven.svg' },
          { label: 'Knit', value: 'knit', preview: '/textures/knit.svg' },
          { label: 'Carbon', value: 'carbon', preview: '/textures/carbon.svg' },
          { label: 'Wood', value: 'wood', preview: '/textures/wood.svg' },
        ],
      },
      {
        kind: 'number',
        key: 'texture_depth_mm',
        label: 'Texture depth',
        unit: 'mm',
        min: 0.2,
        max: 2.5,
        step: 0.1,
        defaultValue: 0.8,
      },
      {
        kind: 'number',
        key: 'texture_spacing_mm',
        label: 'Texture spacing',
        unit: 'mm',
        min: 1,
        max: 8,
        step: 0.25,
        defaultValue: 3,
      },
    ],
  },
];

export function getProduct(type: ProductType): ProductDefinition {
  const product = products.find((item) => item.type === type);
  if (!product) throw new Error(`Unknown product type: ${type}`);
  return product;
}

export function getDefaultParams(product: ProductDefinition): ProductParams {
  return Object.fromEntries(
    product.params.map((param) => [param.key, param.defaultValue]),
  );
}
